title: Tony js
description: Android / Java / Kotlin

url: https://tonys.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html

social:
   github: tonyjs
   email: pkojun09@gmail.com

google_analytics: "UA-103626585-1"
